NAME = sfl
SRCS = main.cpp
OBJS = $(SRCS:.cpp=.o)
GG = c++
GGFLAGS = -Wall -Wextra -Werror -std=c++98 

$(NAME): $(OBJS)
	$(GG) $(GGFLAGS) $(OBJS) -o $(NAME)

all: $(NAME)

clean:
	rm -f $(OBJS)

fclean: clean
	rm -f $(NAME)

re: fclean all
